baseurl: ""
repository: p-j-anderson/p-j-anderson.github.io

collections:
  songs:
    output: true
    permalink: /songs/:path
  videos:
    output: true
    permalink: /videos/:path
  projects:
    output: true
    permalink: /projects/:path


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "songs"
    values:
      layout: "media"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
