baseurl: ""
repository: p-j-anderson/p-j-anderson.github.io

featured:
  project: /projects
  video: /videos
  song: /songs
  post: /posts

social:
  github: https://github.com/p-j-anderson
  youtube: https://youtube.com/user/mrandepaul
  linkedin: https://linkedin.com/p-j-anderson
  instagram: https://www.instagram.com/andepaulj/
  twitter: https://twitter.com/andepaulj
  medium: https://medium.com/@andepaulj

collections:
  songs:
    output: true
    permalink: /songs/:path
  videos:
    output: true
    permalink: /videos/:path
  projects:
    output: true
    permalink: /projects/:path


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "songs"
    values:
      layout: "media"
  - scope:
      path: ""
    values:
      layout: "default"

google_analytics: UA-158057573-1

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
